swagger: '2.0'
info:
  title: petstore.swagger.wordnik.com
  version: 1.0.0
host: petstore.swagger.wordnik.com
basePath: /api
schemes:
  - http
paths:
  /pet:
    put:
      consumes:
        - application/json
      parameters:
        - description: Pet object that needs to be updated in the store
          in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Pet'
      responses:
        '200':
          description: No response was specified
        '400':
          description: Invalid ID supplied
        '404':
          description: Pet not found
        '405':
          description: Validation exception
      operationId: updatePet
      summary: Update an existing pet
  /pet/findByStatus:
    get:
      produces:
        - application/json
        - application/xml
        - text/html
        - text/plain
      parameters:
        - collectionFormat: multi
          description: Status values that need to be considered for filter
          in: query
          items:
            enum:
              - available
              - pending
              - sold
            type: string
          name: status
          required: true
          type: array
      responses:
        '200':
          description: No response was specified
          schema:
            items:
              $ref: '#/definitions/Pet'
            type: array
        '400':
          description: Invalid status value
      description: Multiple status values can be provided with comma seperated strings
      operationId: findPetsByStatus
      summary: Finds Pets by status
  /pet/findByTags:
    get:
      produces:
        - application/json
        - application/xml
        - text/html
        - text/plain
      parameters:
        - collectionFormat: multi
          description: Tags to filter by
          in: query
          items:
            type: string
          name: tags
          required: true
          type: array
      responses:
        '200':
          description: No response was specified
          schema:
            items:
              $ref: '#/definitions/Pet'
            type: array
        '400':
          description: Invalid tag value
      deprecated: true
      description: >-
        Muliple tags can be provided with comma seperated strings. Use tag1,
        tag2, tag3 for testing.
      operationId: findPetsByTags
      summary: Finds Pets by tags
  /pet/uploadImage:
    post:
      consumes:
        - application/octet-stream
      parameters:
        - in: body
          name: body
          schema:
            format: binary
            type: string
      responses:
        '200':
          description: No response was specified
      security:
        - oauth2:
            - 'write:pets'
            - 'read:pets'
      operationId: uploadFile
      summary: uploads an image
  '/pet/{petId}':
    delete:
      parameters:
        - description: Pet id to delete
          in: path
          name: petId
          required: true
          type: string
      responses:
        '200':
          description: No response was specified
        '400':
          description: Invalid pet value
      security:
        - oauth2:
            - 'write:pets'
      operationId: deletePet
      summary: Deletes a pet
    get:
      produces:
        - application/json
        - application/xml
        - text/html
        - text/plain
      parameters:
        - default: 1
          description: ID of pet that needs to be fetched
          format: int64
          in: path
          maximum: 100000
          minimum: 1
          name: petId
          required: true
          type: integer
      responses:
        '200':
          description: No response was specified
          schema:
            $ref: '#/definitions/Pet'
        '400':
          description: Invalid ID supplied
        '404':
          description: Pet not found
      description: Returns a pet based on ID
      operationId: getPetById
      summary: Find pet by ID
    patch:
      consumes:
        - application/json
        - application/xml
      produces:
        - application/json
        - application/xml
      parameters:
        - description: ID of pet that needs to be fetched
          in: path
          name: petId
          required: true
          type: string
        - description: Pet object that needs to be added to the store
          in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Pet'
      responses:
        '200':
          description: No response was specified
          schema:
            items:
              $ref: '#/definitions/Pet'
            type: array
        '400':
          description: Invalid tag value
      security:
        - oauth2:
            - 'write:pets'
      operationId: partialUpdate
      summary: partial updates to a pet
    post:
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - description: ID of pet that needs to be updated
          in: path
          name: petId
          required: true
          type: string
        - description: Updated name of the pet
          in: formData
          name: name
          type: string
        - description: Updated status of the pet
          in: formData
          name: status
          type: string
      responses:
        '200':
          description: No response was specified
        '405':
          description: Invalid input
      security:
        - oauth2:
            - 'write:pets'
      operationId: updatePetWithForm
      summary: Updates a pet in the store with form data
definitions:
  Animal:
    discriminator: type
    properties:
      id:
        type: integer
      type:
        type: string
    required:
      - id
      - type
    type: object
  Cat:
    allOf:
      - properties:
          likesMilk:
            type: boolean
        required:
          - likesMilk
        type: object
      - $ref: '#/definitions/Animal'
  Category:
    properties:
      id:
        format: int64
        type: integer
      name:
        type: string
    type: object
  Pet:
    properties:
      tags:
        items:
          $ref: '#/definitions/Tag'
        type: array
      category:
        $ref: '#/definitions/Category'
      id:
        default: 1
        description: unique identifier for the pet
        format: int64
        maximum: 100
        minimum: 0
        type: integer
      name:
        type: string
      photoUrls:
        items:
          type: string
        type: array
      status:
        description: pet status in the store
        enum:
          - available
          - pending
          - sold
        type: string
    required:
      - id
      - name
    type: object
  Tag:
    properties:
      id:
        format: int64
        type: integer
      name:
        type: string
    type: object
x-components: {}

